language: objective-c
osx_image: xcode8.3
rvm:
- 2.3
install:
- "./Scripts/install.sh"
script:
- "./Scripts/build.sh"
notifications:
  email: false
  slack:
    secure: WxK1lCxC8TYWgbZgBliY9gUj24CvFxYuimTI9hJCfR039gBBJGQV9e9BwKQyG9E5R8BanbqOEFbVAmLc7D+MtQvfbqXbyhJU03dfebcQ7rd0cxyJuaTujLpJDJr5mzKMGsRy4BG+7SduJkSs9l/3OPojiLpysLnAiI9Tz9GjzYqT1OWwGnkwKwdSlEqwMLxtNb5cbxbX+vx7HVisbnI61b1n0MnBLXXj19z/tdMammSpc46Epc51XnRdWNUKrKwyhrk9od/kve5eg4K2gITq6NqF6kMVHs6NoNjtqMxLJMw261PBaPOeXfeNVFKshzCw+pN0lJ6698b0Wz9OJZQ/j5dZfQ/iEllIKeD8OS0F+fxfdpXzvmvdXrrVf1ae8+XoQqhS+Mhv8eG2CvuzGjUeQHAngjdLpRUVUZ9yxsAJsExhBreFYqp22yCN7yVpZuI5gSpDyn8qnQwCpk2PiEtwJbLHE56iMieE4V3A4J4KCxGSud4GxZzM+dx/2Y01vKp9yL5i/UnIPVznPEKZiAuEOnpNmhktigY8b/dcxgLTHUw1gx+Zqme9WPqRXZQYkHCjDqoWiNvFt0othwVSOnt7vhyG2zDmKw7HQTW1PdNehO8cZrxG08GBHte5myqRx4Ry0I+TgBcGPwkQ3U+LhFwwNQf1ZeIkcCKItsvN16NWWV0=
